//twitterkeys
exports.token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
exports.secret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
exports.consumerKey = "XXXXXXXXXXXXXXXXXXXXX";
exports.consumerSecret = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

//turntable keys
exports.AUTH = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
exports.USERID = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
exports.ROOMID = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';

